### ISSUE TITLE
Task `deploy:fail` not found

### ISSUE THREAD

**Issue by wiljanslofstra** [lorisleiva/laravel-deployer#13]
First of all I love your library, it's really easy to setup!

I've followed the docs for integrating Slack in ```deploy.php```. But I've run into the issue that on running ```php artisan deploy``` it throws an error:

```
 [InvalidArgumentException] Task `deploy:fail` not found                        

 #0 /builds/cms/cms/vendor/deployer/deployer/src/Collection/Collection.php(30): 
 Deployer\Task\TaskCollection->throwNotFound('deploy:fail')                     
 #1 /builds/cms/cms/vendor/deployer/deployer/src/functions.php(193):            
 Deployer\Collection\Collection->get('deploy:fail')                             
 #2 /builds/cms/cms/vendor/lorisleiva/laravel-deployer/.build/deploy.php(54):   
 Deployer\after('deploy:fail', 'slack:notify:fa...')                            
 #3 /builds/cms/cms/vendor/deployer/deployer/src/Deployer.php(325):             
 require('/builds/cms/cms...')                                                  
 #4 [internal function]: Deployer\Deployer::Deployer\{closure}()                
 #5 /builds/cms/cms/vendor/deployer/deployer/src/Deployer.php(326):             
 call_user_func(Object(Closure))                                                
 #6 /builds/cms/cms/vendor/deployer/deployer/bin/dep(120):                      
 Deployer\Deployer::run('master', '/builds/cms/cms...')                         
 #7 {main}
```

It happens in the ```after``` function from Deployer:

```
function after($it, $that)
{
    $deployer = Deployer::get();
    $afterTask = $deployer->tasks->get($it);

    $afterTask->addAfter($that);
}
```

The problem only exists on the ```slack:notify:failure``` task, the other Slack notification tasks work as expected.

Using:
- laravel-deployer => 0.2.1

If you need any more information to debug the problem I love to hear it!

Thanks!

**Comment by wiljanslofstra** [comment]
It works great, thanks! 😀
