### ISSUE TITLE
QuestionHelper exception

### ISSUE THREAD

**Issue by nagi1** [lorisleiva/laravel-deployer#163]
**I have this strange error on fresh installed Laravel 6.5.**

My machine run on Windows 8.1

on local machine

> php artisan deploy:init

Terminal output

`***********************************************
*     🚀  Let's configure your deployment!     *
***********************************************

 Aborted.`

I get this error in Laravel.log

`[2020-02-27 10:00:01] local.ERROR: Aborted. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Aborted. at C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Helper\\QuestionHelper.php:137)
[stacktrace]
#0 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Helper\\QuestionHelper.php(81): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk(Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\Question))
#1 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Style\\SymfonyStyle.php(360): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\Question))
#2 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Style\\SymfonyStyle.php(267): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion(Object(Symfony\\Component\\Console\\Question\\Question))
#3 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php(144): Symfony\\Component\\Console\\Style\\SymfonyStyle->ask(Object(Symfony\\Component\\Console\\Question\\Question), '')
#4 C:\\wamp\\www\\projectx\\vendor\\lorisleiva\\laravel-deployer\\src\\LaravelDeployer\\Commands\\DeployInit.php(93): Illuminate\\Console\\Command->ask('Repository URL', '')
#5 C:\\wamp\\www\\projectx\\vendor\\lorisleiva\\laravel-deployer\\src\\LaravelDeployer\\Commands\\DeployInit.php(51): Lorisleiva\\LaravelDeployer\\Commands\\DeployInit->defineRepositoryUrl()
#6 C:\\wamp\\www\\projectx\\vendor\\lorisleiva\\laravel-deployer\\src\\LaravelDeployer\\Commands\\DeployInit.php(32): Lorisleiva\\LaravelDeployer\\Commands\\DeployInit->configureBuilder()
#7 [internal function]: Lorisleiva\\LaravelDeployer\\Commands\\DeployInit->handle()
#8 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#9 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#14 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Application.php(1012): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Lorisleiva\\LaravelDeployer\\Commands\\DeployInit), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 C:\\wamp\\www\\projectx\\vendor\\symfony\\console\\Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 C:\\wamp\\www\\projectx\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 C:\\wamp\\www\\projectx\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} `

**Comment by nagi1** [comment]
It was a PHP 7.4.0 bug fixed in PHP 7.4.1.

updated it and everything working now :)
